# # base image
# FROM node:alpine

# # directory
# WORKDIR '/app'

# # copu package.json
# COPY package.json .

# # install dependencies
# RUN npm install

# # copy all the files
# COPY . .

# CMD [ "npm", "run", "start" ]

FROM node:alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
COPY . .
CMD [ "npm", "run", "start" ]